### ISSUE TITLE
hijacked connection

### ISSUE THREAD

**Issue by rmsj** [aglyzov/wschan#2]
Getting error on the server side.
Using httprouter.
It works correctly with my other client implementation.
Using ws-machine, I got

http: response.WriteHeader on hijacked connection
http: response.Write on hijacked connection

**Comment by aglyzov** [comment]
can you please come up with a minimal example to reproduce it?

**Comment by rmsj** [comment]
That was the best request ever.
While trying to prepare it, I managed to sort the problem, on my server - not on ws-machine.
Thanks heaps.
